# Generated by Gemini

import os
import csv
import shutil

# --- 配置项 ---
# 使用相对路径，确保脚本在哪里运行都能找到文件
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_FILE = os.path.join(BASE_DIR, 'links.csv')
TEMPLATE_FILE = os.path.join(BASE_DIR, 'template.html')

# 【白名单】清理时绝对不能删除的文件/文件夹
# 如果你以后在 s/ 下放了图片文件夹，记得加进来
WHITELIST_FILES = ['build.py', 'links.csv', 'template.html', 'CNAME', '.git', 'README.md']
# ----------------

def build_links():
    print(f"工作目录: {BASE_DIR}")

    # 1. 读取模板
    if not os.path.exists(TEMPLATE_FILE):
        print(f"错误: 找不到模板文件 {TEMPLATE_FILE}")
        return
    with open(TEMPLATE_FILE, 'r', encoding='utf-8') as f:
        template_content = f.read()

    # 2. 【核心变化】清理旧的生成文件夹 (保留白名单文件)
    # 遍历 /s/ 目录下的所有东西
    for item in os.listdir(BASE_DIR):
        item_path = os.path.join(BASE_DIR, item)
        
        # 如果是文件，或者是白名单里的名字，直接跳过，不删
        if item in WHITELIST_FILES or os.path.isfile(item_path):
            continue
        
        # 剩下的都是旧的短链文件夹，删除之
        if os.path.isdir(item_path):
            try:
                shutil.rmtree(item_path)
                # print(f"清理旧目录: {item}") # 调试用
            except Exception as e:
                print(f"删除失败 {item}: {e}")

    # 3. 读取 CSV 并生成
    if not os.path.exists(CSV_FILE):
        print(f"错误: 找不到数据文件 {CSV_FILE}")
        return

    count = 0
    with open(CSV_FILE, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 2: continue
            
            slug = row[0].strip()
            url = row[1].strip()
            
            # 安全检查：防止 slug 包含 .. 或 / 导致写到父目录去
            if '..' in slug or '/' in slug or '\\' in slug:
                print(f"跳过非法短链名: {slug}")
                continue

            # 目标目录: s/my-blog
            slug_dir = os.path.join(BASE_DIR, slug)
            os.makedirs(slug_dir, exist_ok=True)

            # 写入 index.html
            html_output = template_content.replace('__TARGET_URL__', url)
            output_file = os.path.join(slug_dir, 'index.html')
            
            with open(output_file, 'w', encoding='utf-8') as out:
                out.write(html_output)
            
            print(f"[Create] /s/{slug} -> {url}")
            count += 1

    print(f"\n构建完成! 都在 /s/ 目录下，共 {count} 个。")

if __name__ == '__main__':
    build_links()